# Generated by Django 4.1.1 on 2023-02-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brandname',
            field=models.CharField(max_length=100, null='false'),
            preserve_default='false',
        ),
    ]
