# Generated by Django 4.1.7 on 2023-03-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_dealer_dealer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_hr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_week',
            field=models.FloatField(default=0.0),
        ),
    ]
