# Generated by Django 4.1.7 on 2023-03-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_car_price_per_hr_car_price_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_price',
            field=models.FloatField(default=0.0),
        ),
    ]
