# Generated by Django 4.1.7 on 2023-03-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_car_fuel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='price_per_day',
        ),
    ]
