# Generated by Django 4.1.7 on 2023-03-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_car_mileage_car_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.IntegerField(default=0),
        ),
    ]
