# Generated by Django 4.1.7 on 2023-03-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='dealer',
            name='firstname',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='dealer',
            name='lastname',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
