# Generated by Django 4.1.7 on 2023-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customer_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='firstname',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
