# Generated by Django 4.1.1 on 2023-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_car_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='bags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='bluetooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='carkit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='childseat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='roof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='tis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='radio',
            field=models.BooleanField(default=False),
        ),
    ]
