# Generated by Django 4.1.1 on 2023-03-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_car_ac_car_bags_car_bluetooth_car_carkit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.BooleanField(default=False)),
                ('bags', models.BooleanField(default=False)),
                ('carkit', models.BooleanField(default=False)),
                ('childseat', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('roof', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('tis', models.BooleanField(default=False)),
            ],
        ),
    ]
